#!/usr/bin/env bash
set -Eeuo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
page="$root/image/package/usr/share/msfixit-shopos/admin-console/public/oobe.php"
helper="$root/image/package/usr/local/sbin/msfixit-oobe-apply"
sudoers="$root/image/package/etc/sudoers.d/msfixit-shopos-oobe"
php -l "$page"
python3 -m py_compile "$helper"
grep -Fq "const STEPS=['welcome','locale','network','identity','license','apps','summary','apply','complete']" "$page"
grep -Fq "hash_equals(csrf()" "$page"
grep -Fq "password_hash(\$p1,PASSWORD_DEFAULT)" "$page"
grep -Fq "proc_open(\$cmd" "$page"
grep -Fq "'bypass_shell'=>true" "$page"
grep -Fq "filter_var(\$ip,FILTER_VALIDATE_IP" "$page"
grep -Fq "Professional und Enterprise werden erst nach einer gültig signierten Lizenz" "$page"
grep -Fq "Einstellungen prüfen und Einrichtung starten" "$page"
grep -Fq 'if set(data)!=ALLOWED' "$helper"
grep -Fq 'first-boot setup already completed' "$helper"
grep -Fq 'request.is_symlink()' "$helper"
grep -Fq '(st.st_mode & 0o022)' "$helper"
grep -Fq 'os.replace(tmp,path)' "$helper"
grep -Fxq 'www-data ALL=(root) NOPASSWD: /usr/local/sbin/msfixit-oobe-apply /run/shopos-oobe-*' "$sudoers"
! grep -Eq '(shell_exec|system\(|passthru\(|eval\(|bash -c|sh -c|curl|wget|apt |dnf |yum )' "$page" "$helper"
! grep -RiE '(PRIVATE KEY|master[_ -]?key|universal bypass)' "$page" "$helper" "$sudoers"
printf 'PASS: first-boot OOBE is allowlisted, CSRF protected, shell-free, single-use and atomically persisted.\n'
