<?php
declare(strict_types=1);
session_name('SHOPOSADMIN');
session_set_cookie_params(['lifetime'=>0,'path'=>'/admin/','secure'=>!empty($_SERVER['HTTPS']),'httponly'=>true,'samesite'=>'Strict']);
session_start();
header('X-Frame-Options: DENY'); header('X-Content-Type-Options: nosniff'); header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'none'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"); header('Cache-Control: no-store');
if(($_SESSION['authenticated']??false)!==true){header('Location: /admin/');exit;}
function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function csrf():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['csrf'];}
function helper(array $args,int $timeout=120):array{
 $cmd=array_merge(['sudo','-n','/usr/local/sbin/msfixit-update-center'],$args);
 $p=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,['PATH'=>'/usr/sbin:/usr/bin:/sbin:/bin'],['bypass_shell'=>true]);
 if(!is_resource($p))return[1,'Dienst konnte nicht gestartet werden.'];
 $out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($p);
 return[$code,trim($code===0?$out:$err)];
}
$message='';$kind='info';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals(csrf(),(string)($_POST['csrf']??''))){http_response_code(403);exit('Ungültige Anfrage.');}
 $action=(string)($_POST['action']??'');
 $allowed=['check-system','check-apps','start-system-update','reboot','update-app','update-all-apps'];
 if(!in_array($action,$allowed,true)){http_response_code(400);$message='Unbekannte Aktion.';$kind='error';}
 elseif(in_array($action,['start-system-update','reboot','update-app','update-all-apps'],true)&&(string)($_POST['confirm']??'')!=='yes'){$message='Bitte bestätige die Aktion ausdrücklich.';$kind='error';}
 else{
  $args=[$action];if($action==='update-app')$args[]=(string)($_POST['app_id']??'');
  [$code,$detail]=helper($args,in_array($action,['update-app','update-all-apps'],true)?650:150);
  $success=['check-system'=>'Systemprüfung abgeschlossen.','check-apps'=>'App-Releases wurden geprüft und signierte Pakete bereitgestellt.','start-system-update'=>'Systemupdate läuft jetzt im Hintergrund.','reboot'=>'Neustart wurde ausgelöst.','update-app'=>'App wurde aktualisiert.','update-all-apps'=>'Alle bereitliegenden Apps wurden aktualisiert.'];
  $message=$code===0?($success[$action]??'Aktion abgeschlossen.'):'Aktion fehlgeschlagen: '.($detail?:'Unbekannter Fehler.');$kind=$code===0?'success':'error';
 }
}
[$sc,$raw]=helper(['status']);$status=['system'=>['transaction'=>[],'job'=>[],'reboot_required'=>false],'apps'=>[]];
if($sc===0){$decoded=json_decode($raw,true);if(is_array($decoded))$status=$decoded;}
$tx=$status['system']['transaction']??[];$job=$status['system']['job']??[];$running=in_array((string)($job['active_state']??''),['active','activating','reloading'],true);
$apps=is_array($status['apps']??null)?$status['apps']:[];$ready=array_values(array_filter($apps,fn($a)=>($a['update_package_ready']??false)===true));
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="8"><title>ShopOS Update Center</title>
<style>:root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1120px;margin:auto;padding:24px}.top,.row,.actions{display:flex;gap:16px}.top,.row{justify-content:space-between;align-items:center}.back{color:#44506a;text-decoration:none}h1{font-size:clamp(30px,5vw,48px);margin:8px 0}.muted,.lead{color:#667187}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px;margin-top:22px}.card{background:#fff;border:1px solid #dfe6f0;border-radius:20px;padding:22px;box-shadow:0 8px 28px #1720330a}.wide{grid-column:1/-1}.row{padding:13px 0;border-bottom:1px solid #edf1f6}.badge{display:inline-flex;padding:7px 11px;border-radius:999px;font-weight:800;font-size:13px;background:#e9f8ef;color:#136b38}.busy{background:#eef4ff;color:#2156d9}.warn{background:#fff2df;color:#8a4c00}.button{border:0;border-radius:12px;padding:12px 16px;background:#2156d9;color:#fff;font-weight:800}.secondary{background:#172033}.danger{background:#a52a2a}.actions{flex-wrap:wrap;margin-top:18px}.confirm{display:flex;gap:9px;align-items:flex-start;margin:12px 0;color:#4f5b70;font-size:14px}.notice{padding:14px 16px;border-radius:14px;margin:18px 0}.success{background:#e9f8ef;color:#136b38}.error{background:#fff0f0;color:#8a1f1f}.progress{height:12px;border-radius:999px;background:#e8edf5;overflow:hidden;margin:14px 0}.progress span{display:block;height:100%;width:65%;background:#2156d9}@media(max-width:650px){.shell{padding:16px}.top,.row{align-items:flex-start;flex-direction:column}.button{width:100%}.actions{display:block}.actions form{margin:10px 0}}</style></head><body><main class="shell">
<div class="top"><div><a class="back" href="/admin/?view=dashboard">← Control Center</a><h1>Update Center</h1><p class="lead">System und Apps wie in einem klassischen Update Center prüfen und aktualisieren – ohne neu zu flashen.</p></div><span class="badge <?=$running?'busy':''?>"><?=$running?'Update läuft':'Bereit'?></span></div>
<?php if($message!==''):?><div class="notice <?=e($kind)?>" role="status"><?=e($message)?></div><?php endif;?>
<section class="grid"><article class="card"><h2>ShopOS-System</h2><div class="row"><span>Aktiver Slot</span><strong><?=e((string)($tx['active_slot']??'unbekannt'))?></strong></div><div class="row"><span>Zustand</span><strong><?=e((string)($tx['state']??'unbekannt'))?></strong></div><div class="row"><span>Installierte Sequenz</span><strong><?=e((string)($tx['installed_sequence']??0))?></strong></div><?php if($running):?><div class="progress"><span></span></div><p class="muted">Download, Signaturprüfung und Schreiben in den inaktiven Slot laufen im Hintergrund.</p><?php endif;?><div class="actions"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="check-system"><button class="button secondary">Nach Systemupdates suchen</button></form><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="start-system-update"><label class="confirm"><input type="checkbox" name="confirm" value="yes" required>Update herunterladen, prüfen und installieren.</label><button class="button" <?=$running?'disabled':''?>>Herunterladen und installieren</button></form></div></article>
<article class="card"><h2>Neustart &amp; Rollback</h2><p class="muted">Der neue Slot wird testweise gestartet. Nach drei fehlgeschlagenen Starts schaltet ShopOS automatisch zurück.</p><span class="badge <?=($status['system']['reboot_required']??false)?'warn':''?>"><?=($status['system']['reboot_required']??false)?'Neustart erforderlich':'Kein Neustart offen'?></span><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="reboot"><label class="confirm"><input type="checkbox" name="confirm" value="yes" required>Gerät jetzt kontrolliert neu starten.</label><button class="button danger">Jetzt neu starten</button></form></article>
<article class="card wide"><div class="top"><div><h2>App-Updates</h2><p class="muted">Das Update Center sucht in deinem GitHub-Release nach Paketen für bereits installierte Apps. Vor der Installation wird jedes Paket kryptografisch geprüft.</p></div><span class="badge"><?=count($ready)?> bereit</span></div><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="check-apps"><button class="button secondary">Nach App-Updates suchen</button></form>
<?php if(!$apps):?><p class="muted">Noch keine installierten Apps oder Updatepakete gefunden.</p><?php else:foreach($apps as $app):?><div class="row"><div><strong><?=e((string)($app['id']??''))?></strong><div class="muted">Installierte Version: <?=e((string)($app['installed_version']??'unbekannt'))?></div></div><?php if(($app['update_package_ready']??false)===true):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="update-app"><input type="hidden" name="app_id" value="<?=e((string)$app['id'])?>"><input type="hidden" name="confirm" value="yes"><button class="button">Aktualisieren</button></form><?php else:?><span class="badge">Aktuell</span><?php endif;?></div><?php endforeach;if($ready):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="update-all-apps"><label class="confirm"><input type="checkbox" name="confirm" value="yes" required>Alle bereitliegenden signierten App-Updates installieren.</label><button class="button">Alle Apps aktualisieren</button></form><?php endif;endif;?></article></section></main></body></html>
