device:
  layer: rpi5
  hostname: msfixit-shopos
  user1: shopadmin
  user1sudo: passwd
  user1groups: adm,users

locale:
  default: de_AT.UTF-8
  keyboard_keymap: de
  keyboard_layout: German
  timezone: Europe/Vienna

ieee80211:
  regdom: AT

image:
  layer: image-rpios
  boot_part_size: 400%
  root_part_size: 1000%
  compression: xz

layer:
  base: trixie-minbase

packages:
  - packages/msfixit-shopos_arm64.deb
